default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: root
  reconnect: true
  host: localhost

development:
  <<: *default
  database: sweety_development

test:
  <<: *default
  database: sweety_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: sweety_production